import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import AttractionImage from '../components/AttractionImage.jsx';
import { readAttractionState, updateItinerary, trackAttractionEvent } from '../lib/attractionsClient.js';

export default function AttractionsTripPage() {
  const [items, setItems] = useState(() => readAttractionState().itinerary);
  useEffect(() => { const handler = (event) => setItems(event.detail.itinerary); window.addEventListener('bookingcart:attractions-state', handler); return () => window.removeEventListener('bookingcart:attractions-state', handler); }, []);
  const save = (next) => { setItems(next); updateItinerary(next); };
  const move = (index, direction) => { const target = index + direction; if (target < 0 || target >= items.length) return; const next = [...items]; [next[index], next[target]] = [next[target], next[index]]; save(next); };
  return <main className="min-h-screen bg-slate-50 pb-20 pt-24 dark:bg-slate-950 dark:text-white"><div className="mx-auto max-w-5xl px-4 sm:px-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">Personal field notes</p><h1 className="text-4xl font-black">Your attraction trip</h1><p className="mt-2 text-slate-500">A plan, not a reservation. Confirm opening hours and availability before visiting.</p></div><div className="flex gap-2"><button onClick={() => window.print()} className="rounded-xl border border-slate-200 bg-white px-4 py-3 font-bold dark:border-slate-700 dark:bg-slate-900">Print plan</button><Link to="/attractions/results" className="rounded-xl bg-emerald-600 px-4 py-3 font-bold text-white">Add attractions</Link></div></div>
    {!items.length ? <div className="mt-10 rounded-3xl border border-slate-200 bg-white p-12 text-center dark:border-slate-700 dark:bg-slate-900"><i className="ph ph-map-trifold text-4xl text-emerald-600" /><h2 className="mt-3 text-xl font-black">Your trip is open</h2><p className="mt-2 text-slate-500">Add landmarks, museums, parks, and bookable experiences from any destination.</p></div> : <ol className="mt-8 space-y-4">{items.map((entry,index) => <li key={entry.id} className="grid gap-4 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-[120px_1fr_auto] dark:border-slate-700 dark:bg-slate-900"><AttractionImage image={entry.attraction.image} name={entry.attraction.name} className="h-28 w-full rounded-2xl object-cover" /><div><p className="text-xs font-bold uppercase text-emerald-700">Stop {index + 1} · {entry.attraction.category}</p><h2 className="text-xl font-black">{entry.attraction.name}</h2><div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="text-xs font-bold text-slate-500">Visit date and time<input type="datetime-local" value={entry.visitAt || ''} onChange={(e) => save(items.map((item) => item.id === entry.id ? { ...item, visitAt: e.target.value } : item))} className="mt-1 w-full rounded-lg border border-slate-200 bg-transparent p-2 dark:border-slate-700" /></label><label className="text-xs font-bold text-slate-500">Note<input value={entry.note || ''} onChange={(e) => save(items.map((item) => item.id === entry.id ? { ...item, note: e.target.value.slice(0,240) } : item))} placeholder="Meeting point, reminder…" className="mt-1 w-full rounded-lg border border-slate-200 bg-transparent p-2 dark:border-slate-700" /></label></div></div><div className="flex gap-1 sm:flex-col"><button onClick={() => move(index,-1)} disabled={index === 0} aria-label={`Move ${entry.attraction.name} earlier`} className="rounded-lg border px-3 py-2 disabled:opacity-30">↑</button><button onClick={() => move(index,1)} disabled={index === items.length - 1} aria-label={`Move ${entry.attraction.name} later`} className="rounded-lg border px-3 py-2 disabled:opacity-30">↓</button><button onClick={() => { const next = items.filter((item) => item.id !== entry.id); save(next); trackAttractionEvent('itinerary_removed', entry.attraction); }} aria-label={`Remove ${entry.attraction.name}`} className="rounded-lg border px-3 py-2 text-rose-600">×</button></div></li>)}</ol>}
  </div></main>;
}
